name: Daily Gold Price Analysis

on:
  schedule:
    # Runs every day at 1:00 AM UTC (6:30 AM IST)
    - cron: '0 1 * * *'
  
  # Allows manual triggering
  workflow_dispatch:

jobs:
  analyze-gold-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Gold Price Analysis
      run: python main.py
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        METAL_API_KEY: ${{ secrets.METAL_API_KEY }}
